version: '3'

services:
  mongodb:
    image: mongo:4.2.1-bionic
    restart: always
    volumes:
      - db:/data/db
    networks:
      - node-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - '8888:8081'
    restart: always
    depends_on:
      - mongodb
    networks:
      - node-network

volumes:
  db:

networks:
  node-network:
    driver: bridge
