version: '3'

services:
  funny-movie-frontend-prod:
    container_name: funny-movie-web-prod
    build:
      context: ./
      dockerfile: DockerFile.prod
      args:
        NEXT_PUBLIC_API_URL: http://13.212.82.60:3001/api/v1
    restart: always
    ports:
      - 3000:3000
    networks:
      - node-network
  # node-api-prod:
  #   container_name: node-api-prod
  #   command: yarn start
  #   build: ./server-node
  #   image: node-app
  #   environment:
  #     - mongodb://127.0.0.1:27017/FunnyMovie
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - ./server-node:/app/server-node/src
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - node-network
