version: '3'

services:
  funny-movie-frontend-prod:
    container_name: funny-movie-web-prod
    build:
      context: ./
      dockerfile: DockerFile.prod
      args:
        NEXT_PUBLIC_API_URL: http://13.212.82.60:3001/api/v1
    restart: always
    ports:
      - 3000:3000
    networks:
      - my-network
  node-server:
    image: node-server
    container_name: node-server
    command: yarn start
    build: ./server-node
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb-server
      - ME_CONFIG_MONGODB_PORT=27017
      - MONGO_URL=mongodb://mongodb-server:27017/FunnyMovie
    ports:
      - 3001:3001
    restart: always
    networks:
      - my-network
    depends_on:
      - mongodb-server
