version: '3'

services:
  funny-movie-frontend:
    container_name: funny-movie-web
    build:
      context: ./
      dockerfile: DockerFile.dev
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api/v1
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - node-network
  node-api:
    container_name: node-api
    command: yarn dev
    build: ./server-node
    image: node-app
    volumes:
      - ./server-node:/app/server-node/src
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - MONGO_URL=mongodb://127.0.0.1:27017/FunnyMovie
    ports:
      - 3001:3001
    restart: always
    networks:
      - node-network
    depends_on:
      - mongodb
