version: '3'

services:
  funny-movie-frontend:
    container_name: funny-movie-web
    build:
      context: ./
      dockerfile: DockerFile.dev
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - node-network
  node-api:
    container_name: node-api
    command: yarn dev
    build: ./server
    image: node-app
    environment:
      - MONGO_URL=mongodb://127.0.0.1:27017/FunnyMovie
    depends_on:
      - mongodb
    volumes:
      - ./server:/app/server/src
    restart: always
    ports:
      - 3001:3001
    networks:
      - node-network
