version: '3'

services:
  mongodb:
    image: mongo:4.2.1-bionic
    restart: always
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    networks:
      - node-network
  mongo-express:
    image: mongo-express
    ports:
      - '8888:8081'
    restart: always
    networks:
      - node-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    links:
      - mongodb
    depends_on:
      - mongodb

volumes:
  db:

networks:
  node-network:
    driver: bridge
