version: '3'

services:
  mongodb-server:
    image: mongo:4.2.1-bionic
    restart: always
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    networks:
      - my-network
  mongo-express:
    image: mongo-express
    ports:
      - '8888:8081'
    restart: always
    networks:
      - my-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb-server
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb-server

volumes:
  db:

networks:
  my-network:
    driver: bridge
